name: app_6ringo
description: "6ringo your dream marketplace"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dio: any
  # state management
  flutter_bloc: ^8.1.4
  # comparing flutter objects
  equatable: ^2.0.5
  # service locator
  get_it: ^7.6.7
  # date format
  intl: ^0.19.0
  # local database
  floor: ^1.4.2
  # api request
  retrofit: ^4.1.0
  # hooks
  flutter_hooks: ^0.20.5
  # cache network image
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: 8.1.0
  floor_generator: 1.4.2
  build_runner: 2.4.6

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/roboto/Roboto-Light.ttf
          weight: 300
